#!/usr/bin/env python3
import optparse
import re
import subprocess

def get_arguments():
    #dhlwsh orismatwn tou programmatos anti na ta dinw apo pliktrologio
    parser = optparse.OptionParser()
    parser.add_option("-i", "--interface", dest="interface", help="Interface to change MAC adress")
    parser.add_option("-m", "--mac", dest="new_mac", help="The new MAC adress")
    (options, arguments) =  parser.parse_args()
    if not options.interface:
        parser.error("[-] Give an interface")
    if not options.new_mac:
        parser.error("[-] Give a new MAC")
    return options


def change_mac(interface,new_mac):
    subprocess.call(["ifconfig", interface, "down"])
    subprocess.call(["ifconfig", interface, "hw", "ether", new_mac])
    subprocess.call(["ifconfig", interface, "up"])

def get_current_mac(interface):
    #output of ifconfig
    ifconfig_result = subprocess.check_output(["ifconfig", interface])
    #regular expression for finding the mac adress
    mac_adress_search_result = re.search(r"\w\w:\w\w:\w\w:\w\w:\w\w:\w\w", ifconfig_result)
    if mac_adress_search_result:
        return mac_adress_search_result.group(0)
    else:
        print("[-] Could not read MAC address.")

#get arguments -i -m
options=get_arguments()
#show the current mac
current_mac = get_current_mac(options.interface)
print("[-] Current MAC = "+str(current_mac))
#change the macc
change_mac(options.interface,options.new_mac)
#show the new mac which is now the current 
current_mac = get_current_mac(options.interface)

if current_mac == options.new_mac :
    print("[-] MAC was changed successfully to "+ current_mac)
else:
    print("[-] MAC did not get changed")
